name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: barrel-craft
          changelog-types: '[
            {"type": "feat", "section": "Features", "hidden": false},
            {"type": "fix", "section": "Bug Fixes", "hidden": false},
            {"type": "chore", "section": "Miscellaneous", "hidden": false},
            {"type": "docs", "section": "Documentation", "hidden": false},
            {"type": "style", "section": "Styles", "hidden": false},
            {"type": "refactor", "section": "Code Refactoring", "hidden": false},
            {"type": "perf", "section": "Performance Improvements", "hidden": false},
            {"type": "test", "section": "Tests", "hidden": false}
          ]'

  publish-npm:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}